import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react';
import InformationBar from '@/src/components/InformationBar';
import SearchBar from '@/src/components/SearchBar';


export default function Home(props) {
  const api_url = 'https://geo.ipify.org/api/v1?';
  const api_key = process.env.NEXT_PUBLIC_IPIFY_API_KEY;
  const [ipAddress, setIpAddress] = useState(props.ip.ip)
  const [ip, setIp] = useState(null)


  useEffect(() => {
    const url = `${api_url}apiKey=${api_key}&ipAddress=${ipAddress}`
    async function fetchIp() {
      const response = await fetch(url);
      const ip = await response.json();
      if (ip.code == 422) {
        console.log(ip.messages)
        setIp('error')
      } else {
        setIp(ip);
      }
    }
    fetchIp();
  }, [ipAddress])

  if (!ip) {
    return <p>Loading...</p>;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <SearchBar setIpAddress={setIpAddress} />
        <InformationBar ip={ip}/>
      </main>
    </>
  )
}

export async function getServerSideProps() { 
  const res = await fetch('https://api.ipify.org/?format=json');
  const ip = await res.json()

  return {props: {ip}}
}